const exBody9to5 = {
     isSingle: false,
     year: 0,
     month: 0,
     day: 0,
     startHour: 0,
     startMin: 0,
     endHour: 0,
     endMin: 0,
     fromYear: '',
     fromMonth: 2,
     fromDay: 13,
     fromStartHour: 9,
     fromStartMin: 0,
     fromEndHour: 17,
     fromEndMin: 0,
     toYear: '',
     toMonth: 2,
     toDay: 13,
     toStartHour: 17,
     toStartMin: 0,
     toEndHour: 9,
     toEndMin: 0
   };


const exBodyWeekday = {
     isSingle: false,
     year: 0,
     month: 0,
     day: 0,
     startHour: 0,
     startMin: 0,
     endHour: 0,
     endMin: 0,
   fromYear: '',
   fromMonth: 2,
   fromDay: 13,
   fromStartHour: 9,
   fromStartMin: 0,
   fromEndHour: 17,
   fromEndMin: 0,
   toYear: '',
   toMonth: 2,
   toDay: 15,
   toStartHour: 9,
   toStartMin: 0,
   toEndHour: 17,
   toEndMin: 0
};

const exBodyDinner = {
     isSingle: false,
     year: 0,
     month: 0,
     day: 0,
     startHour: 0,
     startMin: 0,
     endHour: 0,
     endMin: 0,
    fromYear: '',
    fromMonth: 2,
    fromDay: 14,
    fromStartHour: 17,
    fromStartMin: 0,
    fromEndHour: 21,
    fromEndMin: 0,
    toYear: '',
    toMonth: 2,
    toDay: 14,
    toStartHour: 9,
    toStartMin: 0,
    toEndHour: 17,
    toEndMin: 0
};

const exBodyValentines = {
     isSingle: false,
     year: 0,
     month: 0,
     day: 0,
     startHour: 0,
     startMin: 0,
     endHour: 0,
     endMin: 0,
    fromYear: '',
    fromMonth: 2,
    fromDay: 14,
    fromStartHour: 17,
    fromStartMin: 0,
    fromEndHour: 21,
    fromEndMin: 0,
    toYear: '',
    toMonth: 2,
    toDay: 7,
    toStartHour: 17,
    toStartMin: 0,
    toEndHour: 21,
    toEndMin: 0
};

const exBodySingleTime = {
  isSingle: true,
  year: 2020,
  month: 1,
  day: 31,
  startHour: 18,
  startMin: 50,
  endHour: 19,
  endMin: 0,
  fromYear: 0,
  fromMonth: 0,
  fromDay: 0,
  fromStartHour: 0,
  fromStartMin: 0,
  fromEndHour: 0,
  fromEndMin: 0,
  toYear: 0,
  toMonth: 0,
  toDay: 0,
  toStartHour: 0,
  toStartMin: 0,
  toEndHour: 0,
  toEndMin: 0
};

module.exports = {
  exBody9to5,
  exBodyWeekday,
  exBodyDinner,
  exBodyValentines,
  exBodySingleTime
};