const exBody9to5 = {
     isSingle: false,
     year: 0,
     month: 0,
     day: 0,
     startHour: 0,
     startMin: 0,
     endHour: 0,
     endMin: 0,
     fromYear: '',
     fromMonth: '',
     fromDay: 13,
     fromStartHour: 9,
     fromStartMin: 0,
     fromEndHour: 17,
     fromEndMin: 0,
     toYear: '',
     toMonth: '',
     toDay: 13,
     toStartHour: 17,
     toStartMin: 0,
     toEndHour: 9,
     toEndMin: 0
   };


const exBodyWeekday = {
     isSingle: false,
     year: 0,
     month: 0,
     day: 0,
     startHour: 0,
     startMin: 0,
     endHour: 0,
     endMin: 0,
   fromYear: '',
   fromMonth: '',
   fromDay: 13,
   fromStartHour: 9,
   fromStartMin: 0,
   fromEndHour: 17,
   fromEndMin: 0,
   toYear: '',
   toMonth: '',
   toDay: 15,
   toStartHour: 9,
   toStartMin: 0,
   toEndHour: 17,
   toEndMin: 0
};

const exBodyDinner = {
     isSingle: false,
     year: 0,
     month: 0,
     day: 0,
     startHour: 0,
     startMin: 0,
     endHour: 0,
     endMin: 0,
    fromYear: '',
    fromMonth: '',
    fromDay: 14,
    fromStartHour: 9,
    fromStartMin: 0,
    fromEndHour: 17,
    fromEndMin: 0,
    toYear: '',
    toMonth: '',
    toDay: 14,
    toStartHour: 17,
    toStartMin: 0,
    toEndHour: 21,
    toEndMin: 0
};

const exBodyValentines = {
     isSingle: false,
     year: 0,
     month: 0,
     day: 0,
     startHour: 0,
     startMin: 0,
     endHour: 0,
     endMin: 0,
    fromYear: '',
    fromMonth: '',
    fromDay: 14,
    fromStartHour: 17,
    fromStartMin: 0,
    fromEndHour: 21,
    fromEndMin: 0,
    toYear: '',
    toMonth: '',
    toDay: 7,
    toStartHour: 17,
    toStartMin: 0,
    toEndHour: 21,
    toEndMin: 0
};

module.exports = {
  exBody9to5,
  exBodyWeekday,
  exBodyDinner,
  exBodyValentines
};